name: Ubuntu 18.04 Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
            - name: install gcovr
              run: pip install gcovr
            - name: make test
              run: make test
